### ISSUE TITLE
undefined method `attribute?' for "10.23.1.19":String

### ISSUE THREAD

**Issue by Afterglow** [ismell/docker-registry-cookbook#19]
Hi,

I am trying to create an AWS node with chef-provisioning and this cookbook. When the cookbook runs using the example docker-registry role I receive the error below.

```
Chef::Mixin::Template::TemplateError (undefined method `attribute?' for "10.23.1.19":String) on line #8:

                 6:   <% end -%>
                 7:   <% @hosts.each do |node| %>
                 8:   server <%= node.attribute?('cloud') ? node['cloud']['local_ipv4'] : node['ipaddress'] %>:<%= @resource.application_port %>;
                 9:   <% end %>
                10: }
```

I looked in the README for the application_nginx cookbook and it says that `hosts: the set of hosts at which to point the load balancer. This overrides the application_server_role parameter to allow search-free static definition as an Array of strings (IP or hostname).`

Since the documentation implies this should be a string and it is I am not sure why it is treated as a node object in the template. Presumably this must be working for other people so I am somewhat confused?

**Comment by ismell** [comment]
I would not use this cookbook anymore. The python docker registry has been deprecated in favor of the new golang version.

Go to https://docs.docker.com/registry/ and use docker to run it.
